### ISSUE TITLE
Can't find "the releases page".

### ISSUE THREAD

**Issue by givrou11** [zaksabeast/XY-All-Friend-Safaris-Patch#2]
I'm just a player who has little experience of using game patch and is new to coding,
I've downloaded the whole patch file, trying to follow your instructions,
while just in the first line you said "download code.ips from **the releases page**",
but I can't find where the releases page is.
I've searched the whole pack I've downloaded and still failed to find it.
Besides, I also can't find where "code.ips" file is.
Could you give some advice/instructions? Thanks a lot.

**Comment by zaksabeast** [comment]
Here is the releases page: https://github.com/zaksabeast/XY-All-Friend-Safaris-Patch/releases

"code.ips" is listed under "Assets":
<img width="232" alt="Screenshot 2023-09-04 at 8 05 55 AM" src="https://github.com/zaksabeast/XY-All-Friend-Safaris-Patch/assets/19464008/868be905-233b-4a80-9816-4fdcb67e415b">
