### ISSUE TITLE
Where's the code.ips?

### ISSUE THREAD

**Issue by goggato** [zaksabeast/XY-All-Friend-Safaris-Patch#3]
I can't try out the code without finding where it is, it's not in files provided so I need help if I'm doing something wrong

**Comment by KostaSaizo7** [comment]
https://github.com/zaksabeast/XY-All-Friend-Safaris-Patch/releases/tag/v1.0.0

**Comment by goggato** [comment]
> https://github.com/zaksabeast/XY-All-Friend-Safaris-Patch/releases/tag/v1.0.0

thanks a lot!
edit: I just started using the friend safari and it's working!

**Comment by zaksabeast** [comment]
I'm glad to hear it was resolved!  And thank you for the help, KostaSaizo7!
